//! Drives the built `cua-rs` binary over stdio and checks its MCP surface.
//!
//! # What this can and cannot assert
//!
//! CI holds neither macOS grant, so nothing here may depend on Accessibility or
//! Screen Recording. That rules out every tool that actually reads a window —
//! which sounds like it leaves nothing worth testing, but the two things most
//! likely to break silently are both grant-free:
//!
//! - **The advertised surface.** Tool names and argument schemas are generated by
//!   `#[tool]` macros from types. A renamed field or a tool that stops being
//!   registered is invisible until an agent calls it and fails, and no unit test
//!   covers the wiring between the arg structs and the router.
//! - **The keyboard tier switch.** `press_key`'s capability check
//!   (`cua_hid::parse_chord` in the default pid-only mode, `ax_verb_for_key`
//!   under `CUA_KEY_AX_ONLY=1`) runs before any AX call in both modes, so which
//!   one is active is reachable and assertable with no permissions at all —
//!   this used to be a single "chords are always refused" invariant; it is now
//!   two, one per mode.

use std::io::{BufRead, BufReader, Write};
use std::process::{Command, Stdio};

/// Send a batch of JSON-RPC lines to the binary and collect the responses.
fn talk(args: &[&str], requests: &[&str]) -> Vec<serde_json::Value> {
    talk_with_env(args, &[], requests)
}

/// Like [`talk`], with extra environment variables set on the child — for
/// exercising a `std::env::var`-gated switch like `CUA_KEY_AX_ONLY` without
/// touching the test process's own environment (which `cargo test` shares
/// across parallel test threads and would make this racy).
fn talk_with_env(args: &[&str], env: &[(&str, &str)], requests: &[&str]) -> Vec<serde_json::Value> {
    let exe = env!("CARGO_BIN_EXE_cua-rs");
    let mut child = Command::new(exe)
        .args(args)
        .envs(env.iter().copied())
        .stdin(Stdio::piped())
        .stdout(Stdio::piped())
        .stderr(Stdio::null())
        .spawn()
        .expect("spawn cua-rs");

    {
        let stdin = child.stdin.as_mut().expect("stdin");
        writeln!(
            stdin,
            r#"{{"jsonrpc":"2.0","id":1,"method":"initialize","params":{{"protocolVersion":"2025-06-18","capabilities":{{}},"clientInfo":{{"name":"it","version":"1"}}}}}}"#
        )
        .unwrap();
        writeln!(
            stdin,
            r#"{{"jsonrpc":"2.0","method":"notifications/initialized"}}"#
        )
        .unwrap();
        for r in requests {
            writeln!(stdin, "{r}").unwrap();
        }
        // Closing stdin is what ends the session. Without this the server waits
        // for more frames and the test hangs instead of failing.
    }
    child.stdin.take();

    let stdout = child.stdout.take().expect("stdout");
    let mut out = Vec::new();
    for line in BufReader::new(stdout).lines() {
        let line = line.expect("read line");
        if line.trim().is_empty() {
            continue;
        }
        out.push(serde_json::from_str(&line).expect("responses must be JSON-RPC"));
    }
    let _ = child.wait();
    out
}

fn response(responses: &[serde_json::Value], id: i64) -> &serde_json::Value {
    responses
        .iter()
        .find(|r| r["id"] == id)
        .unwrap_or_else(|| panic!("no response with id {id} in {responses:#?}"))
}

/// Text of a `tools/call` result, whether it succeeded or errored.
fn call_text(responses: &[serde_json::Value], id: i64) -> String {
    response(responses, id)["result"]["content"]
        .as_array()
        .expect("content array")
        .iter()
        .filter_map(|c| c["text"].as_str())
        .collect::<Vec<_>>()
        .join("\n")
}

#[test]
fn advertises_the_expected_tools() {
    let responses = talk(&[], &[r#"{"jsonrpc":"2.0","id":2,"method":"tools/list"}"#]);

    assert_eq!(
        response(&responses, 1)["result"]["serverInfo"]["name"],
        "cua-rs",
        "server must identify itself as cua-rs"
    );

    let tools = response(&responses, 2)["result"]["tools"]
        .as_array()
        .expect("tools array");
    let mut names: Vec<&str> = tools.iter().map(|t| t["name"].as_str().unwrap()).collect();
    names.sort_unstable();

    // Spelled out rather than counted. A count assertion passes when one tool is
    // renamed and another added, which is exactly the break worth catching.
    assert_eq!(
        names,
        [
            "check_permissions",
            "click",
            "click_in_window",
            "drag",
            "find",
            "get_app_state",
            "hover",
            "list_apps",
            "perform_secondary_action",
            "press_key",
            "scroll",
            "select_text",
            "set_value",
            "type_text",
            "wait_for",
        ]
    );
}

#[test]
fn get_app_state_advertises_its_budget_controls() {
    let responses = talk(&[], &[r#"{"jsonrpc":"2.0","id":2,"method":"tools/list"}"#]);
    let tools = response(&responses, 2)["result"]["tools"]
        .as_array()
        .unwrap()
        .clone();
    let state = tools
        .iter()
        .find(|t| t["name"] == "get_app_state")
        .expect("get_app_state");
    let props = &state["inputSchema"]["properties"];

    for key in ["app", "skeleton", "scope_element_id", "include_screenshot"] {
        assert!(
            !props[key].is_null(),
            "get_app_state must advertise {key}; schema was {props:#?}"
        );
    }
}

#[test]
fn every_action_tool_accepts_a_snapshot_id() {
    // The staleness guard is opt-in per call, so it is only usable if every
    // action actually exposes the field. Losing it on one tool would silently
    // remove the guard for that tool alone.
    let responses = talk(&[], &[r#"{"jsonrpc":"2.0","id":2,"method":"tools/list"}"#]);
    let tools = response(&responses, 2)["result"]["tools"]
        .as_array()
        .unwrap()
        .clone();

    for name in [
        "click",
        "set_value",
        "scroll",
        "type_text",
        "select_text",
        "press_key",
        "perform_secondary_action",
    ] {
        let tool = tools
            .iter()
            .find(|t| t["name"] == name)
            .unwrap_or_else(|| panic!("missing tool {name}"));
        assert!(
            !tool["inputSchema"]["properties"]["snapshot_id"].is_null(),
            "{name} must accept snapshot_id"
        );
        assert!(
            !tool["inputSchema"]["properties"]["element_index"].is_null(),
            "{name} must accept element_index"
        );
        // Same reasoning as the staleness guard: verification-after-action is
        // only reachable if every action offers it. A tool that quietly lost the
        // field would send the caller back to `ui_changed` alone, which is the
        // heuristic this exists to work around.
        assert!(
            !tool["inputSchema"]["properties"]["return_state"].is_null(),
            "{name} must accept return_state"
        );
    }
}

#[test]
fn a_chord_is_attempted_via_pid_by_default() {
    // Reachable with no grants: `cua_hid::parse_chord` is pure and runs before
    // `require_trusted`/`resolve`, so this either fails on the missing grant
    // or the missing snapshot depending on the test machine's own TCC state —
    // never on the old "no accessibility equivalent" refusal, because that
    // refusal no longer applies to a chord in the default keyboard tier.
    let responses = talk(
        &[],
        &[
            r#"{"jsonrpc":"2.0","id":3,"method":"tools/call","params":{"name":"press_key","arguments":{"app":"Finder","element_index":"0","key":"cmd+shift+p"}}}"#,
        ],
    );

    assert_eq!(
        response(&responses, 3)["result"]["isError"],
        true,
        "no permission/snapshot means this still fails, just not for lacking an AX verb"
    );
    let text = call_text(&responses, 3);
    assert!(
        !text.contains("does not synthesize shared HID") && !text.contains("no accessibility equivalent"),
        "a chord must not be refused for lacking an AX verb in the default (pid) keyboard tier: {text}"
    );
}

#[test]
fn cua_key_ax_only_restores_the_old_chord_refusal() {
    // The escape hatch back to the pre-pid-tier contract: with it set, a
    // chord is refused by the same `KeyNoAccessibilityEquivalent` message as
    // before this tier existed, and — like the default mode above — that
    // refusal is reachable with no grants because `ax_verb_for_key` is pure
    // and runs before `require_trusted`.
    let responses = talk_with_env(
        &[],
        &[("CUA_KEY_AX_ONLY", "1")],
        &[
            r#"{"jsonrpc":"2.0","id":3,"method":"tools/call","params":{"name":"press_key","arguments":{"app":"Finder","element_index":"0","key":"cmd+shift+p"}}}"#,
        ],
    );

    assert_eq!(
        response(&responses, 3)["result"]["isError"],
        true,
        "a chord must be refused under CUA_KEY_AX_ONLY=1"
    );
    let text = call_text(&responses, 3);
    assert!(
        text.contains("does not synthesize shared HID"),
        "the refusal must make the no-HID contract explicit: {text}"
    );
}

#[test]
fn removed_allow_hid_option_is_rejected() {
    let output = Command::new(env!("CARGO_BIN_EXE_cua-rs"))
        .arg("--allow-hid")
        .output()
        .expect("start cua-rs");
    assert!(!output.status.success());
    let stderr = String::from_utf8_lossy(&output.stderr);
    assert!(stderr.contains("unknown option `--allow-hid`"), "{stderr}");
}

#[test]
fn an_unparsable_element_index_is_rejected_before_any_native_call() {
    let responses = talk(
        &[],
        &[
            r#"{"jsonrpc":"2.0","id":4,"method":"tools/call","params":{"name":"click","arguments":{"app":"Finder","element_index":"twelve"}}}"#,
        ],
    );
    let text = call_text(&responses, 4);
    assert_eq!(response(&responses, 4)["result"]["isError"], true);
    assert!(
        text.contains("whole number"),
        "must explain the format: {text}"
    );
}

#[test]
fn an_action_with_no_target_says_what_is_missing() {
    let responses = talk(
        &[],
        &[
            r#"{"jsonrpc":"2.0","id":5,"method":"tools/call","params":{"name":"click","arguments":{"app":"Finder"}}}"#,
        ],
    );
    let text = call_text(&responses, 5);
    assert_eq!(response(&responses, 5)["result"]["isError"], true);
    assert!(
        text.contains("element_index") && text.contains("x and y"),
        "must name both ways to target: {text}"
    );
}

#[test]
fn the_pointer_tools_advertise_the_button_and_modifier_vocabulary() {
    // These are the only way an agent learns that a right-click or a
    // command-click is available at all, so losing the fields silently would
    // remove the capability from every caller's point of view.
    let responses = talk(&[], &[r#"{"jsonrpc":"2.0","id":2,"method":"tools/list"}"#]);
    let tools = response(&responses, 2)["result"]["tools"]
        .as_array()
        .unwrap()
        .clone();

    for name in ["click", "click_in_window", "drag"] {
        let tool = tools
            .iter()
            .find(|t| t["name"] == name)
            .unwrap_or_else(|| panic!("missing tool {name}"));
        let props = &tool["inputSchema"]["properties"];
        for key in ["button", "modifiers"] {
            assert!(
                !props[key].is_null(),
                "{name} must advertise {key}; schema was {props:#?}"
            );
        }
    }

    // A drag names both ends independently, and either may be an element or a
    // bare pixel. A schema missing one of the four shapes makes that end
    // unreachable.
    let drag = tools.iter().find(|t| t["name"] == "drag").unwrap();
    let props = &drag["inputSchema"]["properties"];
    for key in [
        "from_element_token",
        "from_window_x",
        "from_window_y",
        "to_element_token",
        "to_window_x",
        "to_window_y",
    ] {
        assert!(!props[key].is_null(), "drag must advertise {key}");
    }

    // Scroll's event tier is only reachable if the caller can ask in a
    // distance, which is the one thing accessibility cannot express.
    let scroll = tools.iter().find(|t| t["name"] == "scroll").unwrap();
    assert!(
        !scroll["inputSchema"]["properties"]["pixels"].is_null(),
        "scroll must advertise pixels"
    );
}

#[test]
fn a_bad_button_or_modifier_is_rejected_before_any_native_call() {
    // Runs with no grants: parsing happens in the MCP layer, before the
    // accessibility check.
    let responses = talk(
        &[],
        &[
            r#"{"jsonrpc":"2.0","id":6,"method":"tools/call","params":{"name":"click","arguments":{"app":"Finder","element_index":"1","button":"mouse3"}}}"#,
            r#"{"jsonrpc":"2.0","id":7,"method":"tools/call","params":{"name":"click","arguments":{"app":"Finder","element_index":"1","modifiers":"cmd+clik"}}}"#,
        ],
    );
    let button = call_text(&responses, 6);
    assert_eq!(response(&responses, 6)["result"]["isError"], true);
    assert!(
        button.contains("left") && button.contains("right") && button.contains("middle"),
        "a bad button must list the real ones: {button}"
    );
    let modifier = call_text(&responses, 7);
    assert_eq!(response(&responses, 7)["result"]["isError"], true);
    assert!(
        modifier.contains("clik"),
        "a bad modifier must name the offending token: {modifier}"
    );
}

#[test]
fn a_drag_with_one_end_missing_says_which_end_and_how_to_name_it() {
    let responses = talk(
        &[],
        &[
            r#"{"jsonrpc":"2.0","id":8,"method":"tools/call","params":{"name":"drag","arguments":{"app":"Finder","from_element_index":"3"}}}"#,
        ],
    );
    let text = call_text(&responses, 8);
    assert_eq!(response(&responses, 8)["result"]["isError"], true);
    assert!(
        text.contains("to_element_token") && text.contains("to_window_x"),
        "must name the missing end's own argument spellings: {text}"
    );
}

#[test]
fn a_hover_with_no_destination_says_what_is_missing() {
    let responses = talk(
        &[],
        &[
            r#"{"jsonrpc":"2.0","id":9,"method":"tools/call","params":{"name":"hover","arguments":{"app":"Finder"}}}"#,
        ],
    );
    let text = call_text(&responses, 9);
    assert_eq!(response(&responses, 9)["result"]["isError"], true);
    assert!(
        text.contains("element_token") && text.contains("window_x"),
        "must name both ways to aim a hover: {text}"
    );
}

#[test]
fn every_coordinate_addressed_action_can_cite_the_snapshot_it_was_read_from() {
    // `element_token` guards a stale INDEX. A stale COORDINATE has no such
    // guard available — the pixel still exists on the new frame, it is just
    // covering something else — so the generation number is the only thing
    // that can catch it, and every tool that accepts a raw point has to accept
    // one. `click_in_window`, `drag` and `hover` are all coordinate-first.
    let responses = talk(&[], &[r#"{"jsonrpc":"2.0","id":2,"method":"tools/list"}"#]);
    let tools = response(&responses, 2)["result"]["tools"]
        .as_array()
        .unwrap()
        .clone();

    for name in ["click", "click_in_window", "drag", "hover"] {
        let tool = tools
            .iter()
            .find(|t| t["name"] == name)
            .unwrap_or_else(|| panic!("missing tool {name}"));
        assert!(
            !tool["inputSchema"]["properties"]["snapshot_id"].is_null(),
            "{name} takes a coordinate, so it must accept snapshot_id"
        );
    }
}

#[test]
fn no_action_tool_is_fire_and_forget() {
    // Every action reports what it did — the verb, what it hit, how it was
    // delivered, and (by default) a diff of the window afterwards. A tool that
    // returned nothing would push the caller back onto a blind retry loop, so
    // the field that carries the post-action read has to be on all of them.
    let responses = talk(&[], &[r#"{"jsonrpc":"2.0","id":2,"method":"tools/list"}"#]);
    let tools = response(&responses, 2)["result"]["tools"]
        .as_array()
        .unwrap()
        .clone();

    for name in [
        "click",
        "click_in_window",
        "drag",
        "hover",
        "scroll",
        "set_value",
        "type_text",
        "select_text",
        "press_key",
        "perform_secondary_action",
    ] {
        let tool = tools
            .iter()
            .find(|t| t["name"] == name)
            .unwrap_or_else(|| panic!("missing tool {name}"));
        assert!(
            !tool["inputSchema"]["properties"]["return_state"].is_null(),
            "{name} must offer the post-action read"
        );
    }
}

#[test]
fn instructions_tell_the_client_to_read_before_acting() {
    // The one invariant of this server. If the instructions stop saying it,
    // agents start calling click first and getting NoSnapshot errors.
    let responses = talk(&[], &[]);
    let instructions = response(&responses, 1)["result"]["instructions"]
        .as_str()
        .expect("server must send instructions")
        .to_string();
    assert!(
        instructions.contains("get_app_state"),
        "instructions must name the call that must come first: {instructions}"
    );
}
