//! Drives the built `cua-rs` binary over stdio and checks its MCP surface.
//!
//! # What this can and cannot assert
//!
//! CI holds neither macOS grant, so nothing here may depend on Accessibility or
//! Screen Recording. That rules out every tool that actually reads a window —
//! which sounds like it leaves nothing worth testing, but the two things most
//! likely to break silently are both grant-free:
//!
//! - **The advertised surface.** Tool names and argument schemas are generated by
//!   `#[tool]` macros from types. A renamed field or a tool that stops being
//!   registered is invisible until an agent calls it and fails, and no unit test
//!   covers the wiring between the arg structs and the router.
//! - **The keyboard tier switch.** `press_key`'s capability check
//!   (`cua_hid::parse_chord` in the default pid-only mode, `ax_verb_for_key`
//!   under `CUA_KEY_AX_ONLY=1`) runs before any AX call in both modes, so which
//!   one is active is reachable and assertable with no permissions at all —
//!   this used to be a single "chords are always refused" invariant; it is now
//!   two, one per mode.

use std::io::{BufRead, BufReader, Write};
use std::process::{Command, Stdio};

/// Send a batch of JSON-RPC lines to the binary and collect the responses.
fn talk(args: &[&str], requests: &[&str]) -> Vec<serde_json::Value> {
    talk_with_env(args, &[], requests)
}

/// Like [`talk`], with extra environment variables set on the child — for
/// exercising a `std::env::var`-gated switch like `CUA_KEY_AX_ONLY` without
/// touching the test process's own environment (which `cargo test` shares
/// across parallel test threads and would make this racy).
fn talk_with_env(args: &[&str], env: &[(&str, &str)], requests: &[&str]) -> Vec<serde_json::Value> {
    let exe = env!("CARGO_BIN_EXE_cua-rs");
    let mut child = Command::new(exe)
        .args(args)
        .envs(env.iter().copied())
        .stdin(Stdio::piped())
        .stdout(Stdio::piped())
        .stderr(Stdio::null())
        .spawn()
        .expect("spawn cua-rs");

    {
        let stdin = child.stdin.as_mut().expect("stdin");
        writeln!(
            stdin,
            r#"{{"jsonrpc":"2.0","id":1,"method":"initialize","params":{{"protocolVersion":"2025-06-18","capabilities":{{}},"clientInfo":{{"name":"it","version":"1"}}}}}}"#
        )
        .unwrap();
        writeln!(
            stdin,
            r#"{{"jsonrpc":"2.0","method":"notifications/initialized"}}"#
        )
        .unwrap();
        for r in requests {
            writeln!(stdin, "{r}").unwrap();
        }
        // Closing stdin is what ends the session. Without this the server waits
        // for more frames and the test hangs instead of failing.
    }
    child.stdin.take();

    let stdout = child.stdout.take().expect("stdout");
    let mut out = Vec::new();
    for line in BufReader::new(stdout).lines() {
        let line = line.expect("read line");
        if line.trim().is_empty() {
            continue;
        }
        out.push(serde_json::from_str(&line).expect("responses must be JSON-RPC"));
    }
    let _ = child.wait();
    out
}

fn response(responses: &[serde_json::Value], id: i64) -> &serde_json::Value {
    responses
        .iter()
        .find(|r| r["id"] == id)
        .unwrap_or_else(|| panic!("no response with id {id} in {responses:#?}"))
}

/// Text of a `tools/call` result, whether it succeeded or errored.
fn call_text(responses: &[serde_json::Value], id: i64) -> String {
    response(responses, id)["result"]["content"]
        .as_array()
        .expect("content array")
        .iter()
        .filter_map(|c| c["text"].as_str())
        .collect::<Vec<_>>()
        .join("\n")
}

#[test]
fn advertises_the_expected_tools() {
    let responses = talk(&[], &[r#"{"jsonrpc":"2.0","id":2,"method":"tools/list"}"#]);

    assert_eq!(
        response(&responses, 1)["result"]["serverInfo"]["name"],
        "cua-rs",
        "server must identify itself as cua-rs"
    );

    let tools = response(&responses, 2)["result"]["tools"]
        .as_array()
        .expect("tools array");
    let mut names: Vec<&str> = tools.iter().map(|t| t["name"].as_str().unwrap()).collect();
    names.sort_unstable();

    // Spelled out rather than counted. A count assertion passes when one tool is
    // renamed and another added, which is exactly the break worth catching.
    assert_eq!(
        names,
        [
            "check_permissions",
            "click",
            "click_in_window",
            "find",
            "get_app_state",
            "list_apps",
            "perform_secondary_action",
            "press_key",
            "scroll",
            "select_text",
            "set_value",
            "type_text",
            "wait_for",
        ]
    );
}

#[test]
fn get_app_state_advertises_its_budget_controls() {
    let responses = talk(&[], &[r#"{"jsonrpc":"2.0","id":2,"method":"tools/list"}"#]);
    let tools = response(&responses, 2)["result"]["tools"]
        .as_array()
        .unwrap()
        .clone();
    let state = tools
        .iter()
        .find(|t| t["name"] == "get_app_state")
        .expect("get_app_state");
    let props = &state["inputSchema"]["properties"];

    for key in ["app", "skeleton", "scope_element_id", "include_screenshot"] {
        assert!(
            !props[key].is_null(),
            "get_app_state must advertise {key}; schema was {props:#?}"
        );
    }
}

#[test]
fn every_action_tool_accepts_a_snapshot_id() {
    // The staleness guard is opt-in per call, so it is only usable if every
    // action actually exposes the field. Losing it on one tool would silently
    // remove the guard for that tool alone.
    let responses = talk(&[], &[r#"{"jsonrpc":"2.0","id":2,"method":"tools/list"}"#]);
    let tools = response(&responses, 2)["result"]["tools"]
        .as_array()
        .unwrap()
        .clone();

    for name in [
        "click",
        "set_value",
        "scroll",
        "type_text",
        "select_text",
        "press_key",
        "perform_secondary_action",
    ] {
        let tool = tools
            .iter()
            .find(|t| t["name"] == name)
            .unwrap_or_else(|| panic!("missing tool {name}"));
        assert!(
            !tool["inputSchema"]["properties"]["snapshot_id"].is_null(),
            "{name} must accept snapshot_id"
        );
        assert!(
            !tool["inputSchema"]["properties"]["element_index"].is_null(),
            "{name} must accept element_index"
        );
        // Same reasoning as the staleness guard: verification-after-action is
        // only reachable if every action offers it. A tool that quietly lost the
        // field would send the caller back to `ui_changed` alone, which is the
        // heuristic this exists to work around.
        assert!(
            !tool["inputSchema"]["properties"]["return_state"].is_null(),
            "{name} must accept return_state"
        );
    }
}

#[test]
fn a_chord_is_attempted_via_pid_by_default() {
    // Reachable with no grants: `cua_hid::parse_chord` is pure and runs before
    // `require_trusted`/`resolve`, so this either fails on the missing grant
    // or the missing snapshot depending on the test machine's own TCC state —
    // never on the old "no accessibility equivalent" refusal, because that
    // refusal no longer applies to a chord in the default keyboard tier.
    let responses = talk(
        &[],
        &[
            r#"{"jsonrpc":"2.0","id":3,"method":"tools/call","params":{"name":"press_key","arguments":{"app":"Finder","element_index":"0","key":"cmd+shift+p"}}}"#,
        ],
    );

    assert_eq!(
        response(&responses, 3)["result"]["isError"],
        true,
        "no permission/snapshot means this still fails, just not for lacking an AX verb"
    );
    let text = call_text(&responses, 3);
    assert!(
        !text.contains("does not synthesize shared HID") && !text.contains("no accessibility equivalent"),
        "a chord must not be refused for lacking an AX verb in the default (pid) keyboard tier: {text}"
    );
}

#[test]
fn cua_key_ax_only_restores_the_old_chord_refusal() {
    // The escape hatch back to the pre-pid-tier contract: with it set, a
    // chord is refused by the same `KeyNoAccessibilityEquivalent` message as
    // before this tier existed, and — like the default mode above — that
    // refusal is reachable with no grants because `ax_verb_for_key` is pure
    // and runs before `require_trusted`.
    let responses = talk_with_env(
        &[],
        &[("CUA_KEY_AX_ONLY", "1")],
        &[
            r#"{"jsonrpc":"2.0","id":3,"method":"tools/call","params":{"name":"press_key","arguments":{"app":"Finder","element_index":"0","key":"cmd+shift+p"}}}"#,
        ],
    );

    assert_eq!(
        response(&responses, 3)["result"]["isError"],
        true,
        "a chord must be refused under CUA_KEY_AX_ONLY=1"
    );
    let text = call_text(&responses, 3);
    assert!(
        text.contains("does not synthesize shared HID"),
        "the refusal must make the no-HID contract explicit: {text}"
    );
}

#[test]
fn removed_allow_hid_option_is_rejected() {
    let output = Command::new(env!("CARGO_BIN_EXE_cua-rs"))
        .arg("--allow-hid")
        .output()
        .expect("start cua-rs");
    assert!(!output.status.success());
    let stderr = String::from_utf8_lossy(&output.stderr);
    assert!(stderr.contains("unknown option `--allow-hid`"), "{stderr}");
}

#[test]
fn an_unparsable_element_index_is_rejected_before_any_native_call() {
    let responses = talk(
        &[],
        &[
            r#"{"jsonrpc":"2.0","id":4,"method":"tools/call","params":{"name":"click","arguments":{"app":"Finder","element_index":"twelve"}}}"#,
        ],
    );
    let text = call_text(&responses, 4);
    assert_eq!(response(&responses, 4)["result"]["isError"], true);
    assert!(
        text.contains("whole number"),
        "must explain the format: {text}"
    );
}

#[test]
fn an_action_with_no_target_says_what_is_missing() {
    let responses = talk(
        &[],
        &[
            r#"{"jsonrpc":"2.0","id":5,"method":"tools/call","params":{"name":"click","arguments":{"app":"Finder"}}}"#,
        ],
    );
    let text = call_text(&responses, 5);
    assert_eq!(response(&responses, 5)["result"]["isError"], true);
    assert!(
        text.contains("element_index") && text.contains("x and y"),
        "must name both ways to target: {text}"
    );
}

#[test]
fn instructions_tell_the_client_to_read_before_acting() {
    // The one invariant of this server. If the instructions stop saying it,
    // agents start calling click first and getting NoSnapshot errors.
    let responses = talk(&[], &[]);
    let instructions = response(&responses, 1)["result"]["instructions"]
        .as_str()
        .expect("server must send instructions")
        .to_string();
    assert!(
        instructions.contains("get_app_state"),
        "instructions must name the call that must come first: {instructions}"
    );
}

#[test]
fn the_acting_tools_advertise_the_destructive_confirmation() {
    // The gate is only usable if the parameter that clears it is in the
    // schema. A refusal that names `confirm_destructive` while the tool does
    // not accept it would be an unescapable dead end, which is worse than
    // having no gate at all.
    let responses = talk(&[], &[r#"{"jsonrpc":"2.0","id":2,"method":"tools/list"}"#]);
    let tools = response(&responses, 2)["result"]["tools"]
        .as_array()
        .unwrap()
        .clone();

    for name in ["click", "press_key", "perform_secondary_action"] {
        let tool = tools
            .iter()
            .find(|t| t["name"] == name)
            .unwrap_or_else(|| panic!("missing tool {name}"));
        assert!(
            !tool["inputSchema"]["properties"]["confirm_destructive"].is_null(),
            "{name} must accept confirm_destructive"
        );
    }

    // And the tools that cannot classify anything must not pretend they can.
    // `click_in_window` has no element behind its point, so there is no label
    // to judge and no honest confirmation to ask for.
    let bare = tools
        .iter()
        .find(|t| t["name"] == "click_in_window")
        .expect("click_in_window");
    assert!(
        bare["inputSchema"]["properties"]["confirm_destructive"].is_null(),
        "click_in_window has no label to classify, so it must not offer a confirmation"
    );
}

#[test]
#[ignore = "binds a loopback port and starts a real HTTP server"]
fn http_mode_requires_the_bearer_token() {
    let port = "39331";
    let token = "test-token-not-a-secret";
    let mut child = Command::new(env!("CARGO_BIN_EXE_cua-rs"))
        .arg(port)
        .env("CUA_HTTP_TOKEN", token)
        .stdout(Stdio::null())
        .stderr(Stdio::null())
        .spawn()
        .expect("spawn cua-rs in HTTP mode");
    // Poll rather than sleep a guessed interval: startup does a permission
    // check and spawns the native worker, and a fixed wait either flakes or
    // wastes time on every run.
    let health_code = || -> String {
        let out = Command::new("curl")
            .args([
                "-s",
                "-o",
                "/dev/null",
                "-w",
                "%{http_code}",
                &format!("http://127.0.0.1:{port}/health"),
            ])
            .output()
            .expect("curl");
        String::from_utf8_lossy(&out.stdout).to_string()
    };
    for _ in 0..100 {
        if health_code() == "200" {
            break;
        }
        std::thread::sleep(std::time::Duration::from_millis(100));
    }

    let get = |path: &str, auth: Option<&str>| -> String {
        let mut cmd = Command::new("curl");
        cmd.arg("-s")
            .arg("-o")
            .arg("/dev/null")
            .arg("-w")
            .arg("%{http_code}");
        if let Some(a) = auth {
            cmd.arg("-H").arg(format!("Authorization: {a}"));
        }
        cmd.arg("-X")
            .arg("POST")
            .arg("-H")
            .arg("Content-Type: application/json")
            .arg("-H")
            .arg("Accept: application/json, text/event-stream")
            .arg("--data")
            .arg(r#"{"jsonrpc":"2.0","id":1,"method":"ping"}"#)
            .arg(format!("http://127.0.0.1:{port}{path}"));
        let out = cmd.output().expect("curl");
        String::from_utf8_lossy(&out.stdout).to_string()
    };

    let unauthenticated = get("/mcp", None);
    let wrong = get("/mcp", Some("Bearer wrong"));
    let right = get("/mcp", Some(&format!("Bearer {token}")));

    // /health stays open so a supervisor can probe a server it has no
    // credential for.
    let health = health_code();

    let _ = child.kill();
    let _ = child.wait();

    assert_eq!(unauthenticated, "401", "no header must be refused");
    assert_eq!(wrong, "401", "a wrong token must be refused");
    assert_ne!(right, "401", "the right token must get through");
    assert_eq!(health, "200", "/health must stay open");
}
