//! Drives the built `cua-rs` binary over stdio and checks its MCP surface.
//!
//! # What this can and cannot assert
//!
//! CI holds neither macOS grant, so nothing here may depend on Accessibility or
//! Screen Recording. That rules out every tool that actually reads a window —
//! which sounds like it leaves nothing worth testing, but the two things most
//! likely to break silently are both grant-free:
//!
//! - **The advertised surface.** Tool names and argument schemas are generated by
//!   `#[tool]` macros from types. A renamed field or a tool that stops being
//!   registered is invisible until an agent calls it and fails, and no unit test
//!   covers the wiring between the arg structs and the router.
//! - **The HID refusal.** `press_key` permanently rejecting a chord is
//!   the project's central safety property. It is enforced before any AX call, so
//!   it is reachable and assertable with no permissions at all.

use std::io::{BufRead, BufReader, Write};
use std::process::{Command, Stdio};

/// Send a batch of JSON-RPC lines to the binary and collect the responses.
fn talk(args: &[&str], requests: &[&str]) -> Vec<serde_json::Value> {
    let exe = env!("CARGO_BIN_EXE_cua-rs");
    let mut child = Command::new(exe)
        .args(args)
        .stdin(Stdio::piped())
        .stdout(Stdio::piped())
        .stderr(Stdio::null())
        .spawn()
        .expect("spawn cua-rs");

    {
        let stdin = child.stdin.as_mut().expect("stdin");
        writeln!(
            stdin,
            r#"{{"jsonrpc":"2.0","id":1,"method":"initialize","params":{{"protocolVersion":"2025-06-18","capabilities":{{}},"clientInfo":{{"name":"it","version":"1"}}}}}}"#
        )
        .unwrap();
        writeln!(
            stdin,
            r#"{{"jsonrpc":"2.0","method":"notifications/initialized"}}"#
        )
        .unwrap();
        for r in requests {
            writeln!(stdin, "{r}").unwrap();
        }
        // Closing stdin is what ends the session. Without this the server waits
        // for more frames and the test hangs instead of failing.
    }
    child.stdin.take();

    let stdout = child.stdout.take().expect("stdout");
    let mut out = Vec::new();
    for line in BufReader::new(stdout).lines() {
        let line = line.expect("read line");
        if line.trim().is_empty() {
            continue;
        }
        out.push(serde_json::from_str(&line).expect("responses must be JSON-RPC"));
    }
    let _ = child.wait();
    out
}

fn response(responses: &[serde_json::Value], id: i64) -> &serde_json::Value {
    responses
        .iter()
        .find(|r| r["id"] == id)
        .unwrap_or_else(|| panic!("no response with id {id} in {responses:#?}"))
}

/// Text of a `tools/call` result, whether it succeeded or errored.
fn call_text(responses: &[serde_json::Value], id: i64) -> String {
    response(responses, id)["result"]["content"]
        .as_array()
        .expect("content array")
        .iter()
        .filter_map(|c| c["text"].as_str())
        .collect::<Vec<_>>()
        .join("\n")
}

#[test]
fn advertises_the_expected_tools() {
    let responses = talk(&[], &[r#"{"jsonrpc":"2.0","id":2,"method":"tools/list"}"#]);

    assert_eq!(
        response(&responses, 1)["result"]["serverInfo"]["name"],
        "cua-rs",
        "server must identify itself as cua-rs"
    );

    let tools = response(&responses, 2)["result"]["tools"]
        .as_array()
        .expect("tools array");
    let mut names: Vec<&str> = tools.iter().map(|t| t["name"].as_str().unwrap()).collect();
    names.sort_unstable();

    // Spelled out rather than counted. A count assertion passes when one tool is
    // renamed and another added, which is exactly the break worth catching.
    assert_eq!(
        names,
        [
            "check_permissions",
            "click",
            "click_in_window",
            "find",
            "get_app_state",
            "list_apps",
            "perform_secondary_action",
            "press_key",
            "scroll",
            "select_text",
            "set_value",
            "type_text",
            "wait_for",
        ]
    );
}

#[test]
fn get_app_state_advertises_its_budget_controls() {
    let responses = talk(&[], &[r#"{"jsonrpc":"2.0","id":2,"method":"tools/list"}"#]);
    let tools = response(&responses, 2)["result"]["tools"]
        .as_array()
        .unwrap()
        .clone();
    let state = tools
        .iter()
        .find(|t| t["name"] == "get_app_state")
        .expect("get_app_state");
    let props = &state["inputSchema"]["properties"];

    for key in ["app", "skeleton", "scope_element_id", "include_screenshot"] {
        assert!(
            !props[key].is_null(),
            "get_app_state must advertise {key}; schema was {props:#?}"
        );
    }
}

#[test]
fn every_action_tool_accepts_a_snapshot_id() {
    // The staleness guard is opt-in per call, so it is only usable if every
    // action actually exposes the field. Losing it on one tool would silently
    // remove the guard for that tool alone.
    let responses = talk(&[], &[r#"{"jsonrpc":"2.0","id":2,"method":"tools/list"}"#]);
    let tools = response(&responses, 2)["result"]["tools"]
        .as_array()
        .unwrap()
        .clone();

    for name in [
        "click",
        "set_value",
        "scroll",
        "type_text",
        "select_text",
        "press_key",
        "perform_secondary_action",
    ] {
        let tool = tools
            .iter()
            .find(|t| t["name"] == name)
            .unwrap_or_else(|| panic!("missing tool {name}"));
        assert!(
            !tool["inputSchema"]["properties"]["snapshot_id"].is_null(),
            "{name} must accept snapshot_id"
        );
        assert!(
            !tool["inputSchema"]["properties"]["element_index"].is_null(),
            "{name} must accept element_index"
        );
        // Same reasoning as the staleness guard: verification-after-action is
        // only reachable if every action offers it. A tool that quietly lost the
        // field would send the caller back to `ui_changed` alone, which is the
        // heuristic this exists to work around.
        assert!(
            !tool["inputSchema"]["properties"]["return_state"].is_null(),
            "{name} must accept return_state"
        );
    }
}

#[test]
fn a_chord_is_refused_without_a_shared_hid_escape_hatch() {
    // Reachable with no grants: the refusal happens before any AX call.
    let responses = talk(
        &[],
        &[
            r#"{"jsonrpc":"2.0","id":3,"method":"tools/call","params":{"name":"press_key","arguments":{"app":"Finder","element_index":"0","key":"cmd+shift+p"}}}"#,
        ],
    );

    assert_eq!(
        response(&responses, 3)["result"]["isError"],
        true,
        "a chord must be refused by default"
    );
    let text = call_text(&responses, 3);
    assert!(
        text.contains("does not synthesize shared HID"),
        "the refusal must make the no-HID contract explicit: {text}"
    );
}

#[test]
fn removed_allow_hid_option_is_rejected() {
    let output = Command::new(env!("CARGO_BIN_EXE_cua-rs"))
        .arg("--allow-hid")
        .output()
        .expect("start cua-rs");
    assert!(!output.status.success());
    let stderr = String::from_utf8_lossy(&output.stderr);
    assert!(stderr.contains("unknown option `--allow-hid`"), "{stderr}");
}

#[test]
fn an_unparsable_element_index_is_rejected_before_any_native_call() {
    let responses = talk(
        &[],
        &[
            r#"{"jsonrpc":"2.0","id":4,"method":"tools/call","params":{"name":"click","arguments":{"app":"Finder","element_index":"twelve"}}}"#,
        ],
    );
    let text = call_text(&responses, 4);
    assert_eq!(response(&responses, 4)["result"]["isError"], true);
    assert!(
        text.contains("whole number"),
        "must explain the format: {text}"
    );
}

#[test]
fn an_action_with_no_target_says_what_is_missing() {
    let responses = talk(
        &[],
        &[
            r#"{"jsonrpc":"2.0","id":5,"method":"tools/call","params":{"name":"click","arguments":{"app":"Finder"}}}"#,
        ],
    );
    let text = call_text(&responses, 5);
    assert_eq!(response(&responses, 5)["result"]["isError"], true);
    assert!(
        text.contains("element_index") && text.contains("x and y"),
        "must name both ways to target: {text}"
    );
}

#[test]
fn instructions_tell_the_client_to_read_before_acting() {
    // The one invariant of this server. If the instructions stop saying it,
    // agents start calling click first and getting NoSnapshot errors.
    let responses = talk(&[], &[]);
    let instructions = response(&responses, 1)["result"]["instructions"]
        .as_str()
        .expect("server must send instructions")
        .to_string();
    assert!(
        instructions.contains("get_app_state"),
        "instructions must name the call that must come first: {instructions}"
    );
}
